config/routes.rb
CSVSimpleForm::Application.routes.draw do
  root to: "basic#edit"
  post "basic", to: "basic#update", as: :basic_update
end

app/models/basic.rb
class Basic < ActiveRecord::Base
  attr_accessible :waiver_of_premium, :client_number
  
  attr_accessor :client_side_override
  
  validates :waiver_of_premium, presence: true, inclusion: { in: ["Yes", "No" ] }, if: :client_side_recommended
  validates :client_number, presence: true, if: :client_side_recommended
  
  private
  
  def client_side_recommended
    client_side_override == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/basic_controller.rb
class BasicController < ApplicationController
  def index
    render
  end
  
  def edit
    @basic = Basic.new
    @basic.client_side_override = true
    render
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basic_helper.rb
module BasicHelper
  def translated_text(*args)
    t("#{args.join(".")}")
  end

  def label_with_hint(section, detail)
    "#{label_text(section, detail)} #{translated_text(:simple_form, :label_hints, section, detail)}"
  end

  def label_text(section, detail)
    "#{translated_text(:simple_form, :labels, section, detail)}"
  end
end

app/views/basic/edit.html.haml
= simple_form_for(@basic, :url => basic_update_path(@basic), :method => :post, :validate => true) do |f|
  .form-inputs
    = f.input :waiver_of_premium, required: true, :collection => ["Yes", "No"], :prompt => "Select waiver of premium..."
    = f.input :client_number, required: true, validate: true
  .hr
  .form-actions
    %p  
      = f.button :submit, "Save", id: 'save-button'

app/views/layouts/application.html.haml
!!! Strict
%html{ html_attrs("en_gb") }
  %head
    %title
      Client Side Validations + Simple Form Test
  = stylesheet_link_tag    "application", :media => "all" 
  = javascript_include_tag "application" 
  = csrf_meta_tags 
  %body
    = yield